name: MC_Ability
version: '${project.version}'
main: mc_ability.beadieststar64.mc_ability.MC_Ability
api-version: 1.19

commands:

  MC_Ability_PassiveSkill:
    aliases: ShowME
    description: コマンド送信者のMinerのEXPを知ることができます
    permission: op
    permission-message: Permission denied
    usage: 使用方法 [MC_Ability_PassiveSkill Show Miner EXP]

  MC_Ability_OpenGUI:
    aliases: open
    description: Test GUIを開きます。
    permission: op
    permission-message: 権限がありません！
    usage: 使用方法 [MC_Ability_OpenGUI]